title: "Viacheslav Savinkov"
description: "DevOps // SRE"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
resume_avatar:                  "true"
resume_avatar_path:             "images/avatar.jpg"
resume_name:                    "Viacheslav Savinkov"
resume_title:                   "DevOps // SRE"
resume_header_contact_info:     "Montreal, Canada // viacheslav@savinkov.me // +1 438 519 1898 // <a href='https://www.linkedin.com/in/viacheslav-savinkov'>linkedin.com/in/viacheslav-savinkov</a>"
display_header_contact_info:    "true"
resume_header_intro:            "Employment: full time, work schedule: full day."
resume_looking_for_work:        "yes"
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_interests:       true

resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/viacheslav-savinkov"
  resume_website_url:           "https://savinkov.me"
resume_print_social_links:      true
